// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/saySheta.proto

package sheta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SayShetaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayShetaRequest) Reset() {
	*x = SayShetaRequest{}
	mi := &file_proto_saySheta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayShetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayShetaRequest) ProtoMessage() {}

func (x *SayShetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_saySheta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayShetaRequest.ProtoReflect.Descriptor instead.
func (*SayShetaRequest) Descriptor() ([]byte, []int) {
	return file_proto_saySheta_proto_rawDescGZIP(), []int{0}
}

func (x *SayShetaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SayShetaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayShetaResponse) Reset() {
	*x = SayShetaResponse{}
	mi := &file_proto_saySheta_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayShetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayShetaResponse) ProtoMessage() {}

func (x *SayShetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_saySheta_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayShetaResponse.ProtoReflect.Descriptor instead.
func (*SayShetaResponse) Descriptor() ([]byte, []int) {
	return file_proto_saySheta_proto_rawDescGZIP(), []int{1}
}

func (x *SayShetaResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_saySheta_proto protoreflect.FileDescriptor

const file_proto_saySheta_proto_rawDesc = "" +
	"\n" +
	"\x14proto/saySheta.proto\x12\x05sheta\"%\n" +
	"\x0fSayShetaRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\",\n" +
	"\x10SayShetaResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2I\n" +
	"\bSaySheta\x12=\n" +
	"\bSaySheta\x12\x16.sheta.SayShetaRequest\x1a\x17.sheta.SayShetaResponse\"\x00B\x16Z\x14v1/sheta/proto;shetab\x06proto3"

var (
	file_proto_saySheta_proto_rawDescOnce sync.Once
	file_proto_saySheta_proto_rawDescData []byte
)

func file_proto_saySheta_proto_rawDescGZIP() []byte {
	file_proto_saySheta_proto_rawDescOnce.Do(func() {
		file_proto_saySheta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_saySheta_proto_rawDesc), len(file_proto_saySheta_proto_rawDesc)))
	})
	return file_proto_saySheta_proto_rawDescData
}

var file_proto_saySheta_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_saySheta_proto_goTypes = []any{
	(*SayShetaRequest)(nil),  // 0: sheta.SayShetaRequest
	(*SayShetaResponse)(nil), // 1: sheta.SayShetaResponse
}
var file_proto_saySheta_proto_depIdxs = []int32{
	0, // 0: sheta.SaySheta.SaySheta:input_type -> sheta.SayShetaRequest
	1, // 1: sheta.SaySheta.SaySheta:output_type -> sheta.SayShetaResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_saySheta_proto_init() }
func file_proto_saySheta_proto_init() {
	if File_proto_saySheta_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_saySheta_proto_rawDesc), len(file_proto_saySheta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_saySheta_proto_goTypes,
		DependencyIndexes: file_proto_saySheta_proto_depIdxs,
		MessageInfos:      file_proto_saySheta_proto_msgTypes,
	}.Build()
	File_proto_saySheta_proto = out.File
	file_proto_saySheta_proto_goTypes = nil
	file_proto_saySheta_proto_depIdxs = nil
}
