// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: proto/saySheta.proto

package sheta

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SaySheta_SaySheta_FullMethodName = "/sheta.SaySheta/SaySheta"
)

// SayShetaClient is the client API for SaySheta service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SayShetaClient interface {
	SaySheta(ctx context.Context, in *SayShetaRequest, opts ...grpc.CallOption) (*SayShetaResponse, error)
}

type sayShetaClient struct {
	cc grpc.ClientConnInterface
}

func NewSayShetaClient(cc grpc.ClientConnInterface) SayShetaClient {
	return &sayShetaClient{cc}
}

func (c *sayShetaClient) SaySheta(ctx context.Context, in *SayShetaRequest, opts ...grpc.CallOption) (*SayShetaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SayShetaResponse)
	err := c.cc.Invoke(ctx, SaySheta_SaySheta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SayShetaServer is the server API for SaySheta service.
// All implementations must embed UnimplementedSayShetaServer
// for forward compatibility.
type SayShetaServer interface {
	SaySheta(context.Context, *SayShetaRequest) (*SayShetaResponse, error)
	mustEmbedUnimplementedSayShetaServer()
}

// UnimplementedSayShetaServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSayShetaServer struct{}

func (UnimplementedSayShetaServer) SaySheta(context.Context, *SayShetaRequest) (*SayShetaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaySheta not implemented")
}
func (UnimplementedSayShetaServer) mustEmbedUnimplementedSayShetaServer() {}
func (UnimplementedSayShetaServer) testEmbeddedByValue()                  {}

// UnsafeSayShetaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SayShetaServer will
// result in compilation errors.
type UnsafeSayShetaServer interface {
	mustEmbedUnimplementedSayShetaServer()
}

func RegisterSayShetaServer(s grpc.ServiceRegistrar, srv SayShetaServer) {
	// If the following call pancis, it indicates UnimplementedSayShetaServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SaySheta_ServiceDesc, srv)
}

func _SaySheta_SaySheta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayShetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SayShetaServer).SaySheta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SaySheta_SaySheta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SayShetaServer).SaySheta(ctx, req.(*SayShetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SaySheta_ServiceDesc is the grpc.ServiceDesc for SaySheta service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SaySheta_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sheta.SaySheta",
	HandlerType: (*SayShetaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaySheta",
			Handler:    _SaySheta_SaySheta_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/saySheta.proto",
}
